name = "primarques-damage-total-x"
compatibility_date = "2025-04-24"

# Este es tu entry-point al Worker proxy
#main = "functions/api/guildRaid/[season].js"

pages_build_output_dir = "OnPremise"

pages_functions_dir = "OnPremise/functions"

# Si tienes assets (el frontend) en esa misma carpeta:
#[site]
#bucket = "."

[vars]
API_KEY = "f29c74cc-fdb6-458e-97f2-383ae722bc87"
DEFAULT_SEASON = "72"